// SPDX-License-Identifier: LGPL-2.1-or-later
/****************************************************************************
 *                                                                          *
 *   Copyright (c) 2025 Kacper Donat <kacper@kadet.net>                     *
 *                                                                          *
 *   This file is part of FreeCAD.                                          *
 *                                                                          *
 *   FreeCAD is free software: you can redistribute it and/or modify it     *
 *   under the terms of the GNU Lesser General Public License as            *
 *   published by the Free Software Foundation, either version 2.1 of the   *
 *   License, or (at your option) any later version.                        *
 *                                                                          *
 *   FreeCAD is distributed in the hope that it will be useful, but         *
 *   WITHOUT ANY WARRANTY; without even the implied warranty of             *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       *
 *   Lesser General Public License for more details.                        *
 *                                                                          *
 *   You should have received a copy of the GNU Lesser General Public       *
 *   License along with FreeCAD. If not, see                                *
 *   <https://www.gnu.org/licenses/>.                                       *
 *                                                                          *
 ***************************************************************************/

#include "PreCompiled.h"

#include "InputHint.h"
#include "InputHintPy.h"

void Gui::registerUserInputEnumInPython(PyObject* module)
{
    using Hint = Gui::InputHint::UserInput;
    constexpr const char* name = "UserInput";

    PyObject* py_enum_module = PyImport_ImportModule("enum");
    if (!py_enum_module) {
        return;
    }

    PyObject* py_constants_dict = PyDict_New();

    // clang-format off
    // this structure is repetition of each and every UserInput enum case
    // it can be regenerated by copying and pasting all entries and performing one substitution:
    // regex search: `(\w+) = .+?,` substitution: `{"$1", $1},`
    const std::map<const char*, InputHint::UserInput> userInputEntries {
        // Modifier
        {"ModifierShift", InputHint::UserInput::ModifierShift},
        {"ModifierCtrl", InputHint::UserInput::ModifierCtrl},
        {"ModifierAlt", InputHint::UserInput::ModifierAlt},
        {"ModifierMeta", InputHint::UserInput::ModifierMeta},

        // Keyboard Keys
        {"KeySpace", InputHint::UserInput::KeySpace},
        {"KeyExclam", InputHint::UserInput::KeyExclam},
        {"KeyQuoteDbl", InputHint::UserInput::KeyQuoteDbl},
        {"KeyNumberSign", InputHint::UserInput::KeyNumberSign},
        {"KeyDollar", InputHint::UserInput::KeyDollar},
        {"KeyPercent", InputHint::UserInput::KeyPercent},
        {"KeyAmpersand", InputHint::UserInput::KeyAmpersand},
        {"KeyApostrophe", InputHint::UserInput::KeyApostrophe},
        {"KeyParenLeft", InputHint::UserInput::KeyParenLeft},
        {"KeyParenRight", InputHint::UserInput::KeyParenRight},
        {"KeyAsterisk", InputHint::UserInput::KeyAsterisk},
        {"KeyPlus", InputHint::UserInput::KeyPlus},
        {"KeyComma", InputHint::UserInput::KeyComma},
        {"KeyMinus", InputHint::UserInput::KeyMinus},
        {"KeyPeriod", InputHint::UserInput::KeyPeriod},
        {"KeySlash", InputHint::UserInput::KeySlash},
        {"Key0", InputHint::UserInput::Key0},
        {"Key1", InputHint::UserInput::Key1},
        {"Key2", InputHint::UserInput::Key2},
        {"Key3", InputHint::UserInput::Key3},
        {"Key4", InputHint::UserInput::Key4},
        {"Key5", InputHint::UserInput::Key5},
        {"Key6", InputHint::UserInput::Key6},
        {"Key7", InputHint::UserInput::Key7},
        {"Key8", InputHint::UserInput::Key8},
        {"Key9", InputHint::UserInput::Key9},
        {"KeyColon", InputHint::UserInput::KeyColon},
        {"KeySemicolon", InputHint::UserInput::KeySemicolon},
        {"KeyLess", InputHint::UserInput::KeyLess},
        {"KeyEqual", InputHint::UserInput::KeyEqual},
        {"KeyGreater", InputHint::UserInput::KeyGreater},
        {"KeyQuestion", InputHint::UserInput::KeyQuestion},
        {"KeyAt", InputHint::UserInput::KeyAt},
        {"KeyA", InputHint::UserInput::KeyA},
        {"KeyB", InputHint::UserInput::KeyB},
        {"KeyC", InputHint::UserInput::KeyC},
        {"KeyD", InputHint::UserInput::KeyD},
        {"KeyE", InputHint::UserInput::KeyE},
        {"KeyF", InputHint::UserInput::KeyF},
        {"KeyG", InputHint::UserInput::KeyG},
        {"KeyH", InputHint::UserInput::KeyH},
        {"KeyI", InputHint::UserInput::KeyI},
        {"KeyJ", InputHint::UserInput::KeyJ},
        {"KeyK", InputHint::UserInput::KeyK},
        {"KeyL", InputHint::UserInput::KeyL},
        {"KeyM", InputHint::UserInput::KeyM},
        {"KeyN", InputHint::UserInput::KeyN},
        {"KeyO", InputHint::UserInput::KeyO},
        {"KeyP", InputHint::UserInput::KeyP},
        {"KeyQ", InputHint::UserInput::KeyQ},
        {"KeyR", InputHint::UserInput::KeyR},
        {"KeyS", InputHint::UserInput::KeyS},
        {"KeyT", InputHint::UserInput::KeyT},
        {"KeyU", InputHint::UserInput::KeyU},
        {"KeyV", InputHint::UserInput::KeyV},
        {"KeyW", InputHint::UserInput::KeyW},
        {"KeyX", InputHint::UserInput::KeyX},
        {"KeyY", InputHint::UserInput::KeyY},
        {"KeyZ", InputHint::UserInput::KeyZ},
        {"KeyBracketLeft", InputHint::UserInput::KeyBracketLeft},
        {"KeyBackslash", InputHint::UserInput::KeyBackslash},
        {"KeyBracketRight", InputHint::UserInput::KeyBracketRight},
        {"KeyAsciiCircum", InputHint::UserInput::KeyAsciiCircum},
        {"KeyUnderscore", InputHint::UserInput::KeyUnderscore},
        {"KeyQuoteLeft", InputHint::UserInput::KeyQuoteLeft},
        {"KeyBraceLeft", InputHint::UserInput::KeyBraceLeft},
        {"KeyBar", InputHint::UserInput::KeyBar},
        {"KeyBraceRight", InputHint::UserInput::KeyBraceRight},
        {"KeyAsciiTilde", InputHint::UserInput::KeyAsciiTilde},

        // misc keys
        {"KeyEscape", InputHint::UserInput::KeyEscape},
        {"KeyTab", InputHint::UserInput::KeyTab},
        {"KeyBacktab", InputHint::UserInput::KeyBacktab},
        {"KeyBackspace", InputHint::UserInput::KeyBackspace},
        {"KeyReturn", InputHint::UserInput::KeyReturn},
        {"KeyEnter", InputHint::UserInput::KeyEnter},
        {"KeyInsert", InputHint::UserInput::KeyInsert},
        {"KeyDelete", InputHint::UserInput::KeyDelete},
        {"KeyPause", InputHint::UserInput::KeyPause},
        {"KeyPrintScr", InputHint::UserInput::KeyPrintScr},
        {"KeySysReq", InputHint::UserInput::KeySysReq},
        {"KeyClear", InputHint::UserInput::KeyClear},

        // cursor movement
        {"KeyHome", InputHint::UserInput::KeyHome},
        {"KeyEnd", InputHint::UserInput::KeyEnd},
        {"KeyLeft", InputHint::UserInput::KeyLeft},
        {"KeyUp", InputHint::UserInput::KeyUp},
        {"KeyRight", InputHint::UserInput::KeyRight},
        {"KeyDown", InputHint::UserInput::KeyDown},
        {"KeyPageUp", InputHint::UserInput::KeyPageUp},
        {"KeyPageDown", InputHint::UserInput::KeyPageDown},

        // modifiers
        {"KeyShift", InputHint::UserInput::KeyShift},
        {"KeyControl", InputHint::UserInput::KeyControl},
        {"KeyMeta", InputHint::UserInput::KeyMeta},
        {"KeyAlt", InputHint::UserInput::KeyAlt},
        {"KeyCapsLock", InputHint::UserInput::KeyCapsLock},
        {"KeyNumLock", InputHint::UserInput::KeyNumLock},
        {"KeyScrollLock", InputHint::UserInput::KeyScrollLock},

        // function keys
        {"KeyF1", InputHint::UserInput::KeyF1},
        {"KeyF2", InputHint::UserInput::KeyF2},
        {"KeyF3", InputHint::UserInput::KeyF3},
        {"KeyF4", InputHint::UserInput::KeyF4},
        {"KeyF5", InputHint::UserInput::KeyF5},
        {"KeyF6", InputHint::UserInput::KeyF6},
        {"KeyF7", InputHint::UserInput::KeyF7},
        {"KeyF8", InputHint::UserInput::KeyF8},
        {"KeyF9", InputHint::UserInput::KeyF9},
        {"KeyF10", InputHint::UserInput::KeyF10},
        {"KeyF11", InputHint::UserInput::KeyF11},
        {"KeyF12", InputHint::UserInput::KeyF12},
        {"KeyF13", InputHint::UserInput::KeyF13},
        {"KeyF14", InputHint::UserInput::KeyF14},
        {"KeyF15", InputHint::UserInput::KeyF15},
        {"KeyF16", InputHint::UserInput::KeyF16},
        {"KeyF17", InputHint::UserInput::KeyF17},
        {"KeyF18", InputHint::UserInput::KeyF18},
        {"KeyF19", InputHint::UserInput::KeyF19},
        {"KeyF20", InputHint::UserInput::KeyF20},
        {"KeyF21", InputHint::UserInput::KeyF21},
        {"KeyF22", InputHint::UserInput::KeyF22},
        {"KeyF23", InputHint::UserInput::KeyF23},
        {"KeyF24", InputHint::UserInput::KeyF24},
        {"KeyF25", InputHint::UserInput::KeyF25},
        {"KeyF26", InputHint::UserInput::KeyF26},
        {"KeyF27", InputHint::UserInput::KeyF27},
        {"KeyF28", InputHint::UserInput::KeyF28},
        {"KeyF29", InputHint::UserInput::KeyF29},
        {"KeyF30", InputHint::UserInput::KeyF30},
        {"KeyF31", InputHint::UserInput::KeyF31},
        {"KeyF32", InputHint::UserInput::KeyF32},
        {"KeyF33", InputHint::UserInput::KeyF33},
        {"KeyF34", InputHint::UserInput::KeyF34},
        {"KeyF35", InputHint::UserInput::KeyF35},

        // Mouse Keys
        {"MouseMove", Hint::MouseMove},
        {"MouseLeft", Hint::MouseLeft},
        {"MouseRight", Hint::MouseRight},
        {"MouseMiddle", Hint::MouseMiddle},
        {"MouseScroll", Hint::MouseScroll},
        {"MouseScrollUp", Hint::MouseScrollUp},
        {"MouseScrollDown", Hint::MouseScrollDown},
    };
    // clang-format on

    // Populate dictionary
    for (const auto& [key, value] : userInputEntries) {
        PyDict_SetItemString(py_constants_dict, key, PyLong_FromLong(static_cast<int>(value)));
    }

    PyObject* py_enum_class = PyObject_CallMethod(py_enum_module, "IntEnum", "sO", name, py_constants_dict);

    Py_CLEAR(py_constants_dict);
    Py_CLEAR(py_enum_module);

    if (py_enum_class && PyModule_AddObject(module, name, py_enum_class) < 0) {
        Py_CLEAR(py_enum_class);
    }
}
