blank_issues_enabled: false
contact_links:
  - name: 💬 START HERE -- FreeCAD Forum
    url: https://codeberg.org/xCAD/xCAD_discussions/issues
    about: You are encouraged to discuss the problem you are seeing on the forum before opening an issue here
